"""Initial migration

Revision ID: 0f6575106ab2
Revises: 
Create Date: 2025-05-19 14:57:51.073784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f6575106ab2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)
    op.create_index(op.f('ix_paises_nombre'), 'paises', ['nombre'], unique=True)
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_index(op.f('ix_provincias_nombre'), 'provincias', ['nombre'], unique=True)
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localidades_id'), 'localidades', ['id'], unique=False)
    op.create_index(op.f('ix_localidades_nombre'), 'localidades', ['nombre'], unique=True)
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('piso', sa.String(), nullable=True),
    sa.Column('dpto', sa.String(), nullable=True),
    sa.Column('entre_calles', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.Integer(), nullable=True),
    sa.Column('barrio', sa.String(), nullable=True),
    sa.Column('localidad_id', sa.Integer(), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidades.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_barrio'), 'direcciones', ['barrio'], unique=False)
    op.create_index(op.f('ix_direcciones_codigo_postal'), 'direcciones', ['codigo_postal'], unique=False)
    op.create_index(op.f('ix_direcciones_id'), 'direcciones', ['id'], unique=False)
    op.create_table('agentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('tipo_documento', postgresql.ENUM('DNI', 'CUIT', 'CUIL', 'PASAPORTE', 'OTRO', name='tipo_documento_enum'), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('licencia', sa.String(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentes_id'), 'agentes', ['id'], unique=False)
    op.create_index(op.f('ix_agentes_numero_documento'), 'agentes', ['numero_documento'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('tipo_documento', postgresql.ENUM('DNI', 'CUIT', 'CUIL', 'PASAPORTE', 'OTRO', name='tipo_documento_enum'), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('genero', postgresql.ENUM('MASCULINO', 'FEMENINO', 'OTRO', name='genero_enum'), nullable=True),
    sa.Column('situacion_fiscal', postgresql.ENUM('RESPONSABLE_INSCRIPTO', 'RESPONSABLE_NO_INSCRIPTO', 'EXENTO', 'CONSUMIDOR_FINAL', 'MONOTRIBUTO', 'NO_RESPONSABLE', 'OTRO', name='situacion_fiscal_enum'), nullable=True),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clientes_apellido'), 'clientes', ['apellido'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_numero_documento'), 'clientes', ['numero_documento'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_numero_documento'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_apellido'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_agentes_numero_documento'), table_name='agentes')
    op.drop_index(op.f('ix_agentes_id'), table_name='agentes')
    op.drop_table('agentes')
    op.drop_index(op.f('ix_direcciones_id'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_codigo_postal'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_barrio'), table_name='direcciones')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_localidades_nombre'), table_name='localidades')
    op.drop_index(op.f('ix_localidades_id'), table_name='localidades')
    op.drop_table('localidades')
    op.drop_index(op.f('ix_provincias_nombre'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    op.drop_index(op.f('ix_paises_nombre'), table_name='paises')
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.drop_table('paises')
    # ### end Alembic commands ###
