"""Se agrega modelo Agente

Revision ID: 21a59fce488f
Revises: db39655f9706
Create Date: 2025-05-19 11:18:06.970258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a59fce488f'
down_revision: Union[str, None] = 'db39655f9706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('DNI', 'CUIT', 'CUIL', 'PASAPORTE', 'OTRO', name='tipo_documento_enum'), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('licencia', sa.String(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentes_id'), 'agentes', ['id'], unique=False)
    op.create_index(op.f('ix_agentes_numero_documento'), 'agentes', ['numero_documento'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agentes_numero_documento'), table_name='agentes')
    op.drop_index(op.f('ix_agentes_id'), table_name='agentes')
    op.drop_table('agentes')
    # ### end Alembic commands ###
