"""Se agrega modelo de Direccion

Revision ID: 9c60caa4b9a3
Revises: d6c4a9bb4ab6
Create Date: 2025-05-17 10:52:58.956428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c60caa4b9a3'
down_revision: Union[str, None] = 'd6c4a9bb4ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('piso', sa.String(), nullable=True),
    sa.Column('dpto', sa.String(), nullable=True),
    sa.Column('entre_calles', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.Integer(), nullable=True),
    sa.Column('barrio', sa.String(), nullable=True),
    sa.Column('localidad_id', sa.Integer(), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['localidad_id'], ['localidades.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_barrio'), 'direcciones', ['barrio'], unique=False)
    op.create_index(op.f('ix_direcciones_codigo_postal'), 'direcciones', ['codigo_postal'], unique=False)
    op.create_index(op.f('ix_direcciones_id'), 'direcciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direcciones_id'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_codigo_postal'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_barrio'), table_name='direcciones')
    op.drop_table('direcciones')
    # ### end Alembic commands ###
