"""crear tablas iniciales

Revision ID: d6c4a9bb4ab6
Revises: 
Create Date: 2025-05-13 16:21:55.644277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c4a9bb4ab6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paises_id'), 'paises', ['id'], unique=False)
    op.create_index(op.f('ix_paises_nombre'), 'paises', ['nombre'], unique=True)
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_index(op.f('ix_provincias_nombre'), 'provincias', ['nombre'], unique=True)
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('provincia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localidades_id'), 'localidades', ['id'], unique=False)
    op.create_index(op.f('ix_localidades_nombre'), 'localidades', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localidades_nombre'), table_name='localidades')
    op.drop_index(op.f('ix_localidades_id'), table_name='localidades')
    op.drop_table('localidades')
    op.drop_index(op.f('ix_provincias_nombre'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    op.drop_index(op.f('ix_paises_nombre'), table_name='paises')
    op.drop_index(op.f('ix_paises_id'), table_name='paises')
    op.drop_table('paises')
    # ### end Alembic commands ###
