"""Create clientes table

Revision ID: db39655f9706
Revises: 0a7e9a8b3637
Create Date: 2025-05-18 18:02:34.144392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db39655f9706'
down_revision: Union[str, None] = '0a7e9a8b3637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.Enum('DNI', 'CUIT', 'CUIL', 'PASAPORTE', 'OTRO', name='tipo_documento_enum'), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', name='genero_enum'), nullable=True),
    sa.Column('situacion_fiscal', sa.Enum('RESPONSABLE_INSCRIPTO', 'RESPONSABLE_NO_INSCRIPTO', 'EXENTO', 'CONSUMIDOR_FINAL', 'MONOTRIBUTO', 'NO_RESPONSABLE', 'OTRO', name='situacion_fiscal_enum'), nullable=True),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_clientes_apellido'), 'clientes', ['apellido'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_clientes_numero_documento'), 'clientes', ['numero_documento'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_numero_documento'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_apellido'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
